"""Memory-spine curator — project events from the stream into MEMORY.md.

Step 2 scope (this commit): the outer shell — argparse, ``fcntl.flock``
acquisition, stream reading, atomic ``MEMORY.md`` rewrite, and the CLI
exit-code contract. The projection function is a stub returning the file
unchanged. Step 3 replaces the stub with per-event-type projectors and
fail-closed marker handling.

CLI contract (documented in ``docs/specs/BILTIQ-003/design.html``):
  $ python3 scripts/_memory_curator.py [--verbose]
  Exit 0 — success (rewritten, or no-op for empty stream).
  Exit 0 — lock held by another process; stdout: {"skipped": "..."}.
  Exit 1 — fail-closed: missing marker; stderr: {"error": "missing_marker", ...}.
  Exit 2 — unrecoverable I/O; stderr: {"error": "io", "detail": ...}.

On success, stdout is one JSON line:
  {"events_seen": N, "events_projected": M, "sections_written": [...]}
"""

from __future__ import annotations

import sys
from pathlib import Path

# When invoked as `python3 scripts/_memory_curator.py`, Python puts the
# script's parent dir (scripts/) on sys.path[0] — not the repo root — so the
# absolute `from scripts.*` import below cannot resolve. Insert the repo root
# (the parent of this file's parent). No-op under module imports or under
# `python3 -m scripts._memory_curator`, where __package__ is already set.
if __name__ == "__main__" and __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import argparse
import fcntl
import json
import logging
import os
import re
import tempfile
from contextlib import contextmanager
from typing import Any, Final, Iterator

from scripts._memory_writer import _resolve_repo_root

logger = logging.getLogger(__name__)

LOCK_RELATIVE_PATH: Final[str] = ".biltiq/.curator.lock"
STREAM_RELATIVE_PATH: Final[str] = ".biltiq/memory-stream.jsonl"
MEMORY_RELATIVE_PATH: Final[str] = "MEMORY.md"
CURATOR_SUPPORTED_VERSION: Final[int] = 1
LOCK_FILE_MODE: Final[int] = 0o600

PROJECTED_EVENT_TYPES: Final[frozenset[str]] = frozenset(
    {"standup_post", "blocker_logged", "commit_metadata", "reflect_note"}
)
EXPECTED_MARKERS: Final[tuple[str, ...]] = (
    "auto:current_focus",
    "auto:code_areas",
    "auto:session_log",
    "manual",
)
_GENERATED_COMMENT: Final[str] = "<!-- generated by scripts/_memory_curator.py; do not hand-edit -->"
_MARKER_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"<!-- (auto:[a-z_]+|manual):(start|end) -->"
)


class CuratorError(Exception):
    """Base error for curator-side failures."""


class MissingMarkerError(CuratorError):
    """Raised when MEMORY.md is missing an expected auto/manual marker pair."""

    def __init__(self, marker: str) -> None:
        super().__init__(f"missing marker: {marker}")
        self.marker = marker


@contextmanager
def _acquire_lock(lock_path: Path) -> Iterator[bool]:
    """Acquire an exclusive non-blocking flock on ``lock_path``.

    Yields ``True`` if the lock was acquired (caller does the work), ``False``
    if another process holds it (caller should print the skipped sentinel and
    exit 0). The fd is unconditionally closed on exit; ``fcntl.flock`` releases
    the lock automatically when the fd closes — including on crash or kill.
    """
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(str(lock_path), os.O_WRONLY | os.O_CREAT, LOCK_FILE_MODE)
    try:
        os.fchmod(fd, LOCK_FILE_MODE)
        try:
            fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            yield False
            return
        try:
            yield True
        finally:
            fcntl.flock(fd, fcntl.LOCK_UN)
    finally:
        os.close(fd)


def _read_events(stream_path: Path) -> list[dict[str, Any]]:
    """Read every JSON-line event in the stream. Skips malformed lines with a WARNING."""
    if not stream_path.exists():
        return []
    events: list[dict[str, Any]] = []
    with stream_path.open("r", encoding="utf-8") as f:
        for lineno, raw in enumerate(f, start=1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                event = json.loads(raw)
            except json.JSONDecodeError as exc:
                logger.warning(
                    "skipping malformed line %d in %s: %s",
                    lineno,
                    stream_path,
                    exc,
                )
                continue
            events.append(event)
    return events


def _find_markers(memory_text: str) -> dict[str, tuple[int, int]]:
    """Locate ``auto:*`` / ``manual`` marker pairs in ``memory_text``.

    Returns ``{marker_name: (content_start, content_end)}`` for each well-formed
    pair, where ``content_start`` is the char index right after the start marker
    and ``content_end`` is the char index right before the end marker. Last-wins
    on duplicates. Pairs with ``end <= start`` are excluded.
    """
    starts: dict[str, int] = {}
    ends: dict[str, int] = {}
    for m in _MARKER_PATTERN.finditer(memory_text):
        name = m.group(1)
        kind = m.group(2)
        if kind == "start":
            starts[name] = m.end()
        else:
            ends[name] = m.start()

    paired: dict[str, tuple[int, int]] = {}
    for name, start_pos in starts.items():
        end_pos = ends.get(name)
        if end_pos is not None and end_pos > start_pos:
            paired[name] = (start_pos, end_pos)
    return paired


def _replace_auto_block(memory_text: str, marker_name: str, new_content: str) -> str:
    """Splice ``new_content`` between ``<!-- {marker_name}:start -->`` and the matching end marker.

    Caller must have verified both markers exist (via :func:`_find_markers`);
    this function raises :class:`MissingMarkerError` as a belt-and-braces
    check if invariants are violated.
    """
    start_marker = f"<!-- {marker_name}:start -->"
    end_marker = f"<!-- {marker_name}:end -->"
    start_idx = memory_text.find(start_marker)
    end_idx = memory_text.find(end_marker)
    if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
        raise MissingMarkerError(marker_name)
    content_start = start_idx + len(start_marker)
    return (
        memory_text[:content_start]
        + "\n" + new_content + "\n"
        + memory_text[end_idx:]
    )


def _render_current_focus(events: list[dict[str, Any]]) -> str:
    """Render ``auto:current_focus`` from the latest ``standup_post`` + all open ``blocker_logged``."""
    standups = [e for e in events if e.get("event_type") == "standup_post"]
    blockers = [e for e in events if e.get("event_type") == "blocker_logged"]
    lines = [_GENERATED_COMMENT]
    if standups:
        latest = standups[-1]
        payload = latest.get("payload") or {}
        date = payload.get("date", "?")
        doing = payload.get("doing") or []
        lines.append(f"**Today ({date}):**")
        for item in doing:
            lines.append(f"- {item}")
    if blockers:
        if standups:
            lines.append("")
        lines.append("**Open blockers:**")
        for b in blockers:
            payload = b.get("payload") or {}
            title = payload.get("title", "?")
            task_id = payload.get("task_id", "?")
            since = payload.get("since", "?")
            lines.append(f"- {title} (task {task_id}, since {since})")
    return "\n".join(lines)


def _render_code_areas(events: list[dict[str, Any]]) -> str:
    """Render ``auto:code_areas`` from ``commit_metadata`` events, sorted by touch count."""
    commits = [e for e in events if e.get("event_type") == "commit_metadata"]
    lines = [_GENERATED_COMMENT]
    file_counts: dict[str, int] = {}
    for c in commits:
        payload = c.get("payload") or {}
        files = payload.get("files_touched") or []
        for f in files:
            if isinstance(f, str):
                file_counts[f] = file_counts.get(f, 0) + 1
    sorted_files = sorted(file_counts.items(), key=lambda x: (-x[1], x[0]))
    for f, count in sorted_files[:20]:
        lines.append(f"- `{f}` ({count}x)")
    return "\n".join(lines)


def _render_session_log(events: list[dict[str, Any]]) -> str:
    """Render ``auto:session_log`` from ``standup_post`` + ``reflect_note`` events in stream order."""
    relevant = [e for e in events if e.get("event_type") in ("standup_post", "reflect_note")]
    lines = [_GENERATED_COMMENT]
    for e in relevant:
        ts = e.get("ts", "?")
        etype = e.get("event_type")
        payload = e.get("payload") or {}
        if etype == "standup_post":
            date = payload.get("date", "?")
            lines.append(f"- {ts}: standup for {date}")
        elif etype == "reflect_note":
            task_id = payload.get("task_id", "?")
            lines.append(f"- {ts}: reflect on {task_id}")
    return "\n".join(lines)


def _project_events(
    events: list[dict[str, Any]],
    memory_text: str,
) -> tuple[str, dict[str, Any]]:
    """Project events into MEMORY.md auto-sections; fail closed if markers missing.

    Steps:
      1. Locate every ``auto:*`` / ``manual`` marker pair. Raise
         :class:`MissingMarkerError` if any expected pair is absent.
      2. Filter events by ``schema_version`` (skip > ``CURATOR_SUPPORTED_VERSION``).
      3. Render each auto-section's content from the relevant events.
      4. Splice the rendered content between the existing markers, leaving
         everything outside the auto markers byte-equal.
      5. Return the new text + stats.
    """
    paired = _find_markers(memory_text)
    for name in EXPECTED_MARKERS:
        if name not in paired:
            raise MissingMarkerError(name)

    eligible = [
        e for e in events
        if isinstance(e, dict) and e.get("schema_version", 1) <= CURATOR_SUPPORTED_VERSION
    ]

    eligible_types = {e.get("event_type") for e in eligible}

    new_text = memory_text
    sections_written: list[str] = []

    new_text = _replace_auto_block(new_text, "auto:current_focus", _render_current_focus(eligible))
    if {"standup_post", "blocker_logged"} & eligible_types:
        sections_written.append("current_focus")

    new_text = _replace_auto_block(new_text, "auto:code_areas", _render_code_areas(eligible))
    if "commit_metadata" in eligible_types:
        sections_written.append("code_areas")

    new_text = _replace_auto_block(new_text, "auto:session_log", _render_session_log(eligible))
    if {"standup_post", "reflect_note"} & eligible_types:
        sections_written.append("session_log")

    projected = sum(1 for e in eligible if e.get("event_type") in PROJECTED_EVENT_TYPES)

    stats: dict[str, Any] = {
        "events_seen": len(events),
        "events_projected": projected,
        "sections_written": sections_written,
    }
    return new_text, stats


def _atomic_write(target: Path, content: str) -> None:
    """Write ``content`` to ``target`` via a sibling temp file + ``os.replace``.

    No partial-write window: readers always see either the old or the new
    file, never a half-written one. Cleans up the temp file if anything
    goes wrong before the replace.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path_str = tempfile.mkstemp(
        prefix=target.name + ".",
        suffix=".tmp",
        dir=str(target.parent),
    )
    tmp_path = Path(tmp_path_str)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(str(tmp_path), str(target))
    finally:
        if tmp_path.exists():
            try:
                tmp_path.unlink()
            except OSError:
                pass


def run(argv: list[str] | None = None) -> int:
    """CLI entry. Returns the process exit code (also see module docstring)."""
    parser = argparse.ArgumentParser(
        description="Project memory-spine events into MEMORY.md",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable INFO logging on stderr",
    )
    args = parser.parse_args(argv)
    if args.verbose:
        logging.basicConfig(level=logging.INFO)

    try:
        root = _resolve_repo_root()
    except RuntimeError as exc:
        sys.stderr.write(json.dumps({"error": "io", "detail": str(exc)}) + "\n")
        return 2

    lock_path = root / LOCK_RELATIVE_PATH
    stream_path = root / STREAM_RELATIVE_PATH
    memory_path = root / MEMORY_RELATIVE_PATH

    with _acquire_lock(lock_path) as acquired:
        if not acquired:
            sys.stdout.write(json.dumps({"skipped": "another curator already running"}) + "\n")
            return 0

        try:
            events = _read_events(stream_path)
            current = memory_path.read_text(encoding="utf-8") if memory_path.exists() else ""
        except OSError as exc:
            sys.stderr.write(json.dumps({"error": "io", "detail": str(exc)}) + "\n")
            return 2

        try:
            new_text, stats = _project_events(events, current)
        except MissingMarkerError as exc:
            sys.stderr.write(json.dumps({"error": "missing_marker", "marker": exc.marker}) + "\n")
            return 1

        if new_text != current:
            try:
                _atomic_write(memory_path, new_text)
            except OSError as exc:
                sys.stderr.write(json.dumps({"error": "io", "detail": str(exc)}) + "\n")
                return 2

        sys.stdout.write(json.dumps(stats) + "\n")
        return 0


if __name__ == "__main__":
    sys.exit(run())
