"""Shared fixtures for ``tests/scripts/``.

Every test that touches the memory-spine modules gets a ``tmp_repo`` fixture
that builds an isolated fake repo under ``tmp_path``, with
``BILTIQ_REPO_ROOT`` redirecting the writer/curator away from the real
``.biltiq/``. An autouse safety fixture asserts the env var, if set, stays
inside ``tmp_path`` for the duration of the test.

Hook tests additionally use the ``git_tmp_repo`` fixture, which extends
``tmp_repo`` with a real ``git init``-ed working tree and a copy of the
``scripts/`` package, so the installer + post-commit hook can run end-to-end.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Final, Iterator

import pytest

SEEDED_MEMORY_MD: Final[str] = """\
# MEMORY.md

<!-- auto:current_focus:start -->
<!-- generated by scripts/_memory_curator.py; do not hand-edit -->
<!-- auto:current_focus:end -->

<!-- auto:code_areas:start -->
<!-- generated by scripts/_memory_curator.py; do not hand-edit -->
<!-- auto:code_areas:end -->

<!-- auto:session_log:start -->
<!-- generated by scripts/_memory_curator.py; do not hand-edit -->
<!-- auto:session_log:end -->

<!-- manual:start -->
## Recent decisions
- Locked the JSONL stream shape in ADR-0001.

## Recently completed
- BILTIQ-001 spec.

## Known issues & gotchas
- (none)

## Open questions
- (none active)
<!-- manual:end -->
"""


@pytest.fixture
def tmp_repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Build a fake repo under tmp_path and redirect writer/curator at it.

    Seeds ``MEMORY.md`` with both auto and manual marker pairs so curator
    tests can exercise the projection contract without re-seeding per-test.
    """
    (tmp_path / ".biltiq").mkdir()
    (tmp_path / "MEMORY.md").write_text(SEEDED_MEMORY_MD, encoding="utf-8")
    monkeypatch.setenv("BILTIQ_REPO_ROOT", str(tmp_path))
    assert Path(os.environ["BILTIQ_REPO_ROOT"]).resolve() == tmp_path.resolve()
    return tmp_path


_REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[2]


@pytest.fixture
def git_tmp_repo(tmp_repo: Path) -> Path:
    """Extend ``tmp_repo`` with a ``git init``-ed working tree and a real ``scripts/`` copy.

    The post-commit hook calls ``git rev-parse --show-toplevel`` and references
    ``$REPO/scripts/_memory_curator.py``, so the hook tests need both a real ``.git``
    and a populated ``scripts/`` tree. Copying (rather than symlinking) the source
    insulates each test from edits a sibling test may make to its own copy
    (e.g. replacing ``_memory_curator.py`` with a sleep stub).
    """
    shutil.copytree(_REPO_ROOT / "scripts", tmp_repo / "scripts")

    subprocess.run(["git", "init", "--quiet"], cwd=tmp_repo, check=True)
    subprocess.run(
        ["git", "config", "user.email", "test@biltiq.invalid"],
        cwd=tmp_repo,
        check=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "BILTIQ Test"],
        cwd=tmp_repo,
        check=True,
    )
    subprocess.run(
        ["git", "commit", "--allow-empty", "--quiet", "-m", "BILTIQ-003: test init"],
        cwd=tmp_repo,
        check=True,
        capture_output=True,
    )
    return tmp_repo


@pytest.fixture(autouse=True)
def _no_real_repo_writes(tmp_path: Path) -> Iterator[None]:
    """Belt-and-braces: assert BILTIQ_REPO_ROOT (when set) stays inside tmp_path."""
    yield
    root = os.environ.get("BILTIQ_REPO_ROOT")
    if root is not None:
        resolved = Path(root).resolve()
        assert resolved.is_relative_to(tmp_path.resolve()), (
            f"BILTIQ_REPO_ROOT={root!r} escaped tmp_path={tmp_path!r}; "
            "a test wrote outside the sandbox."
        )
